bin/gosa-encrypt-passwords, include/class_functions: Fix init vector bug in cred_encrypt() and cred_decrypt().
  ```
  Fatal error: Uncaught Error: Length must be greater than 0 in
  /usr/share/gosa/include/functions.inc:3324 Stack trace:
  #0 /usr/share/gosa/include/functions.inc(3324): openssl_random_pseudo_bytes()
  #1 /usr/share/gosa/include/class_config.inc(310): cred_decrypt()
  #2 /usr/share/gosa/include/class_config.inc(362): config->get_credentials()
  #3 /usr/share/gosa/include/class_configRegistry.inc(408): config->get_ldap_link()
  #4 /usr/share/gosa/include/class_config.inc(453): configRegistry->reload()
  #5 /usr/share/gosa/include/class_config.inc(441): config->load_servers()
  #6 /usr/share/gosa/html/index.php(267): config->set_current()
  #7 {main}
  thrown in /usr/share/gosa/include/functions.inc on line 3324
  ```
  ... because the chosen method (aes-256-ecb) doesn't use an
  initialization vector ($iv) at all, causing its length ($ivlen) to be 0.

  So the encrypt/decrypt implementation seems to have been sort of wrong
  before (and only now with PHP 7.4 (and upwards) an error is thrown).

  See Debian bug:  https://bugs.debian.org/964318